# Generated by Django 3.2 on 2023-07-02 09:14
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'main/fixtures/system_user.json', app_label='main')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
