# Generated by Django 3.2 on 2023-07-02 09:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230702_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.user')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.user')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.user')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.department')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.user')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30)),
                ('order', models.IntegerField()),
                ('code', models.IntegerField()),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.user')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.user')),
            ],
            options={
                'db_table': 'news_category',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=30)),
                ('contents', models.TextField()),
                ('start_on', models.DateField(null=True)),
                ('end_on', models.DateField(null=True)),
                ('no', models.IntegerField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.newscategory')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.user')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.user')),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='AffiliationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_on', models.DateField(null=True)),
                ('end_on', models.DateField(null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.user')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.section')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.user')),
            ],
            options={
                'db_table': 'affiliation_history',
            },
        ),
    ]
