# Generated by Django 3.2 on 2023-07-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_affiliationhistory_department_news_newscategory_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='end_on',
            new_name='publication_on',
        ),
        migrations.RemoveField(
            model_name='news',
            name='start_on',
        ),
    ]
