# Generated by Django 3.2 on 2023-07-02 13:05
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'main/fixtures/init_data.json', app_label='main')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230702_2045'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
