# Generated by Django 3.2 on 2023-07-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230707_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='code',
            new_name='no',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='order',
        ),
        migrations.AddField(
            model_name='product',
            name='no',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='no',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='no',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
