# Generated by Django 3.2 on 2023-07-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230707_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone_no',
            field=models.CharField(default='', max_length=20),
        ),
    ]
