# Generated by Django 3.2 on 2023-07-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230707_0317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_category',
            new_name='ProductCategory',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='store',
            name='brand',
        ),
        migrations.AddField(
            model_name='store',
            name='vendor',
            field=models.ForeignKey(default='2e058930-d930-4c32-940e-53fe147d09e4', on_delete=django.db.models.deletion.PROTECT, to='main.vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='sales_amount',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.storeproduct', unique=True),
        ),
    ]
