# Generated by Django 3.2 on 2023-07-08 23:57
from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'main/fixtures/products.json', app_label='main')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_name'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
